export const environment = {
  production: true,
  dummyOTP: 123456,
  perssionName: "permissionaForHRAlert",
  Appname: "HR Alert Care - Admin",
  hrEmail: "admin@alertltd.com",
  resendOTPTime: 5,
  TOKEN_KEY: "auth-token",
  firstTime: "isFirstTime",
  adminUser: "admin",
  adminPass: "admin",
  activateAdminLoginPopUp: false,
  protocol: "http://",
  apiURL: "185.196.3.147:3000/api/v1",
  imageApiURL: "185.196.3.147:3000",
  // imageApiURL: "localhost:3000",
  // apiURL: "localhost:3000/api/v1",
};
